### ISSUE TITLE
shape size mismatch

### ISSUE THREAD

**Issue by wolyosung** [chenllliang/ATP#1]
Hi, I'm trying your new model to reproduce the result, but your released model's shape is different from the released code.

I downloaded all of your checkpoints, but shell script shows these error messages as follows.

RuntimeError: Error(s) in loading state_dict for AMRBartForConditionalGeneration:
	size mismatch for final_logits_bias: copying a param with shape torch.Size([1, 53631]) from checkpoint, the shape in current model is torch.Size([1, 53587]).
	size mismatch for model.shared.weight: copying a param with shape torch.Size([53631, 1024]) from checkpoint, the shape in current model is torch.Size([53587, 1024]).
	size mismatch for model.encoder.embed_tokens.weight: copying a param with shape torch.Size([53631, 1024]) from checkpoint, the shape in current model is torch.Size([53587, 1024]).
	size mismatch for model.decoder.embed_tokens.weight: copying a param with shape torch.Size([53631, 1024]) from checkpoint, the shape in current model is torch.Size([53587, 1024]).

**Comment by chenllliang** [comment]
Hi, thanks for your information , I am trying to reproduce and fix the error.
Do all models have same error messages? And do you follow the requirement section to create two new enviroments ?

**Comment by wolyosung** [comment]
yes, all models have the same error messages. I did follow all requirements also. It occurred during running intermediate_eval.sh, so I think it has no relation with BLINK.

**Comment by chenllliang** [comment]
I clone the repo and didn't meet the same error as yours. However, I have a guess that your current model doesn't read the ./vocabs/dp_edges.txt file to add vocabulary. There are 45 new token in the file and should be added to the model. According to your error message, the checkpoint has 44 more tokens.   Could you please check the content of dp_edges.txt and check the `init_amr_vocabulary()` function  in  `./spring/spring_amr/tokenization_bart.py`  that whether it loads all additonal vocabs properly.  You can also give me the vocab of your new created model, I'll help check which tokens are missing.

```python

class AMRBartTokenizer
......

def init_amr_vocabulary(self, pred_min=5):
        for tok in [self.bos_token, self.eos_token, self.pad_token, '<mask>', '<unk>']:
            ntok = self.INIT + tok
            i = self.encoder[tok]
            self.decoder[i] = ntok
            del self.encoder[tok]
            self.encoder[ntok] = i

        tokens = []
        for line in Path(ROOT/'data/vocab/predicates.txt').read_text().strip().splitlines():
            tok, count = line.split()
            if int(count) >= pred_min:
                tokens.append(tok)

        # add your vocab for one pretrain_task        
        for tok in Path("../vocabs/dp_edges.txt").read_text().strip().splitlines():
            tokens.append(tok)
        
        for tok in Path(ROOT/'data/vocab/additions.txt').read_text().strip().splitlines():
            tokens.append(tok)

        for tok in Path(ROOT/'data/vocab/recategorizations.txt').read_text().strip().splitlines():
            if not tok.startswith('_'):
                self.recategorizations.add(tok)
            tokens.append(tok)

        if self.use_pointer_tokens:
            for cnt in range(512):
                tokens.append(f"<pointer:{cnt}>")

```

**Comment by chenllliang** [comment]
Hi, Is the problem resolved ? let me know if further help is needed.

**Comment by wolyosung** [comment]
thanks for your guide. It now works. have a nice day.
