### ISSUE TITLE
Missing Amrization Code

### ISSUE THREAD

**Issue by Zoher15** [chenllliang/ATP#2]
Hello @chenllliang!!

Great work :). Could you please upload the code for amrization? [It says "coming soon"](https://github.com/chenllliang/ATP-AMR/blob/main/amrization/train_srl.py).

Thanks!

Zoher

**Comment by chenllliang** [comment]
Hi @Zoher15, sorry for the delay. The amrization code has been uploaded.  : )

Liang

**Comment by Zoher15** [comment]
@chenllliang Thanks! Any reason why it is in zip format?

Best,
Zoher

**Comment by Zoher15** [comment]
@chenllliang  Thanks! I want to create srl-pseudo-amr, and also understand all the steps that you use for creating the graph :) which scripts should I be looking at to do both?

**Comment by chenllliang** [comment]
@Zoher15 I think the get_srl.py does all the process, the outputs are amrized and linearized srl.  The output file can be directly used for training.
